// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkndbekhhiykcmqzkydf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrbmRiZWtoaGl5a2NtcXpreWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MzM2OTksImV4cCI6MjA3MzIwOTY5OX0.ZbKosU34zP_CljCVbBIkmdWy0SwXfcRn5YkqSyT0eOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});